name: f_widget_to_image
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Libraries.
  cupertino_icons: ^1.0.2
  file_picker: 
  path_provider: ^2.0.8
  path: ^1.8.0
  permission_handler: ^10.1.0
  downloads_path_provider_28: ^0.1.2
  # ADDS
  widgets_to_image: any
  text_editor: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Billabong
      fonts:
        - asset: fonts/Billabong.ttf
    - family: GrandHotel
      fonts:
        - asset: fonts/GrandHotel.otf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand.otf
    - family: BeautifulPeople
      fonts:
        - asset: fonts/BeautifulPeople.ttf
    - family: BeautyMountains
      fonts:
        - asset: fonts/BeautyMountains.ttf
    - family: BiteChocolate
      fonts:
        - asset: fonts/BiteChocolate.ttf
    - family: BlackberryJam
      fonts:
        - asset: fonts/BlackberryJam.ttf
    - family: Tomatoes
      fonts:
        - asset: fonts/Tomatoes.ttf
    - family: BunchBlossoms
      fonts:
        - asset: fonts/BunchBlossoms.ttf
    - family: CinderelaRegular
      fonts:
        - asset: fonts/CinderelaRegular.ttf
    - family: Countryside
      fonts:
        - asset: fonts/Countryside.ttf
    - family: Halimun
      fonts:
        - asset: fonts/Halimun.ttf
    - family: LemonJelly
      fonts:
        - asset: fonts/LemonJelly.ttf
    - family: QuiteMagicalRegular
      fonts:
        - asset: fonts/QuiteMagicalRegular.ttf
    - family: TropicalAsianDemoRegular
      fonts:
        - asset: fonts/TropicalAsianDemoRegular.ttf
    - family: VeganStyle
      fonts:
        - asset: fonts/VeganStyle.ttf
